### ISSUE TITLE
Python 3.7.2 has issue of no reponse when select option number?

### ISSUE THREAD

**Issue by colemanlee** [ismailtasdelen/hackertarget#2]
Python 3.7.2 has issue of no reponse when select option number?

>   _               _              _                          _
 | |_   __ _  __ | |__ ___  _ _ | |_  __ _  _ _  __ _  ___ | |_
 | ' \ / _` |/ _|| / // -_)| '_||  _|/ _` || '_|/ _` |/ -_)|  _|
 |_||_|\__,_|\__||_\_\___||_|   \__|\__,_||_|  \__, |\___| \__|
                                                |___/
                 Ismail Tasdelen
 | github.com/ismailtasdelen | linkedin.com/in/ismailtasdelen |

[1] Traceroute
[2] Ping Test
[3] DNS Lookup
[4] Reverse DNS
[5] Find DNS Host
[6] Find Shared DNS
[7] Zone Transfer
[8] Whois Lookup
[9] IP Location Lookup
[10] Reverse IP Lookup
[11] TCP Port Scan
[12] Subnet Lookup
[13] HTTP Header Check
[14] Extract Page Links
[15] Exit

Which option number : 3

D:\Program Files (x86)\Python\Python37-32\apps\hackertarget-master>

**Comment by ismailtasdelen** [comment]
Hi again ( @colemanlee & @Muniy90 )

Our solution :

It seems that there may be something wrong when you use a problem or a problem with your python version. Try to use the tool as in the above example. If not, change your python version.

Thank you for your help :smile:

**Comment by Muniy90** [comment]
Thanks for the reply.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Jan 24, 2019, 10:53 AM by notifications@github.com:
